In [3]:
import numpy
import pandas as pd
import progressbar as pb
import pickle

In [4]:
ratings=pd.read_csv("ratings.csv")
movies=pd.read_csv("movies.csv")
ratings=pd.merge(movies,ratings).drop(columns=["genres","timestamp"])#["genres","timestamp"],axis=1
ratings.head()

   movieId             title  userId  rating
0        1  Toy Story (1995)       1     4.0
1        1  Toy Story (1995)       5     4.0
2        1  Toy Story (1995)       7     4.5
3        1  Toy Story (1995)      15     2.5
4        1  Toy Story (1995)      17     4.5

In [1]:
# R = [
#      [5,3,0,1],
#      [4,0,0,1],
#      [1,1,0,5],
#      [1,0,0,4],
#      [0,1,5,4],
#     ]

# R = numpy.array(R)
# N = len(R)
# M = len(R[0])
# K = 2

# P = numpy.random.rand(N,K)
# Q = numpy.random.rand(M,K)

# nP,nQ = matrix_factorization(R, P, Q, K)
# nR = np.dot(nP, nQ.T)
# nR

In [5]:
user_ratings=ratings.pivot_table(index={'userId'},columns={'title'},values={'rating'})
movie_user_rating_pivot=user_ratings
movie_user_rating_pivot.head()

           rating                                          \
title  '71 (2014) 'Hellboy': The Seeds of Creation (2004)
userId
1             NaN                                     NaN
2             NaN                                     NaN
3             NaN                                     NaN
4             NaN                                     NaN
5             NaN                                     NaN

                                                                             \
title  'Round Midnight (1986) 'Salem's Lot (2004) 'Til There Was You (1997)
userId
1                         NaN                 NaN                       NaN
2                         NaN                 NaN                       NaN
3                         NaN                 NaN                       NaN
4                         NaN                 NaN                       NaN
5                         NaN                 NaN                       NaN

                                                           \
title  'Tis the Season for Love (2015) 'burbs, The (1989)
userId
1                                  NaN                NaN
2                                  NaN                NaN
3                                  NaN                NaN
4                                  NaN                NaN
5                                  NaN                NaN

                                                         \
title  'night Mother (1986) (500) Days of Summer (2009)
userId
1                       NaN                         NaN
2                       NaN                         NaN
3                       NaN                         NaN
4                       NaN                         NaN
5                       NaN                         NaN

                                       \
title  *batteries not included (1987)
userId
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN

                          ...                                              \
title                     ...                    Zulu (2013) [REC] (2007)
userId                    ...
1                         ...                            NaN          NaN
2                         ...                            NaN          NaN
3                         ...                            NaN          NaN
4                         ...                            NaN          NaN
5                         ...                            NaN          NaN

                                              \
title  [REC]² (2009) [REC]³ 3 Génesis (2012)
userId
1                NaN                     NaN
2                NaN                     NaN
3                NaN                     NaN
4                NaN                     NaN
5                NaN                     NaN

                                                                               \
title  anohana: The Flower We Saw That Day - The Movie (2013) eXistenZ (1999)
userId
1                                                     NaN                 NaN
2                                                     NaN                 NaN
3                                                     NaN                 NaN
4                                                     NaN                 NaN
5                                                     NaN                 NaN

                                                                        \
title  xXx (2002) xXx: State of the Union (2005) ¡Three Amigos! (1986)
userId
1             NaN                            NaN                   4.0
2             NaN                            NaN                   NaN
3             NaN                            NaN                   NaN
4             NaN                            NaN                   NaN
5             NaN                            NaN                   NaN


title  À nous la liberté (Freedom for Us) (1931)
userId
1                                            NaN
2                                            NaN
3                                            NaN
4                                            NaN
5                                            NaN

[5 rows x 9719 columns]

In [6]:
user_ratings=user_ratings.fillna(0)
user_ratings.head()

           rating                                          \
title  '71 (2014) 'Hellboy': The Seeds of Creation (2004)
userId
1             0.0                                     0.0
2             0.0                                     0.0
3             0.0                                     0.0
4             0.0                                     0.0
5             0.0                                     0.0

                                                                             \
title  'Round Midnight (1986) 'Salem's Lot (2004) 'Til There Was You (1997)
userId
1                         0.0                 0.0                       0.0
2                         0.0                 0.0                       0.0
3                         0.0                 0.0                       0.0
4                         0.0                 0.0                       0.0
5                         0.0                 0.0                       0.0

                                                           \
title  'Tis the Season for Love (2015) 'burbs, The (1989)
userId
1                                  0.0                0.0
2                                  0.0                0.0
3                                  0.0                0.0
4                                  0.0                0.0
5                                  0.0                0.0

                                                         \
title  'night Mother (1986) (500) Days of Summer (2009)
userId
1                       0.0                         0.0
2                       0.0                         0.0
3                       0.0                         0.0
4                       0.0                         0.0
5                       0.0                         0.0

                                       \
title  *batteries not included (1987)
userId
1                                 0.0
2                                 0.0
3                                 0.0
4                                 0.0
5                                 0.0

                          ...                                              \
title                     ...                    Zulu (2013) [REC] (2007)
userId                    ...
1                         ...                            0.0          0.0
2                         ...                            0.0          0.0
3                         ...                            0.0          0.0
4                         ...                            0.0          0.0
5                         ...                            0.0          0.0

                                              \
title  [REC]² (2009) [REC]³ 3 Génesis (2012)
userId
1                0.0                     0.0
2                0.0                     0.0
3                0.0                     0.0
4                0.0                     0.0
5                0.0                     0.0

                                                                               \
title  anohana: The Flower We Saw That Day - The Movie (2013) eXistenZ (1999)
userId
1                                                     0.0                 0.0
2                                                     0.0                 0.0
3                                                     0.0                 0.0
4                                                     0.0                 0.0
5                                                     0.0                 0.0

                                                                        \
title  xXx (2002) xXx: State of the Union (2005) ¡Three Amigos! (1986)
userId
1             0.0                            0.0                   4.0
2             0.0                            0.0                   0.0
3             0.0                            0.0                   0.0
4             0.0                            0.0                   0.0
5             0.0                            0.0                   0.0


title  À nous la liberté (Freedom for Us) (1931)
userId
1                                            0.0
2                                            0.0
3                                            0.0
4                                            0.0
5                                            0.0

[5 rows x 9719 columns]

In [7]:
with open('testfile', 'rb') as file:
    pickle_model = pickle.load(file)
pickle_model

array([[4.10961697, 4.88782389, 4.18404928, ..., 2.3423878 , 3.84900848,
        1.08671821],
       [3.46157589, 3.93485738, 3.35807414, ..., 1.88686197, 3.15278672,
        0.81365563],
       [0.67961036, 3.66860994, 3.30084332, ..., 1.73984016, 2.0379452 ,
        1.77616325],
       ...,
       [2.98478825, 3.85847572, 3.32021741, ..., 1.84712429, 2.9466528 ,
        0.96145191],
       [3.02704822, 3.77997272, 3.24579413, ..., 1.81032561, 2.92314316,
        0.9007577 ],
       [3.90945853, 4.10450617, 3.48292963, ..., 1.97048088, 3.39438971,
        0.72946006]])

In [9]:
 preds_df = pd.DataFrame(pickle_model, index=user_ratings.index,columns = user_ratings.columns)
 preds_df.head()

           rating                                          \
title  '71 (2014) 'Hellboy': The Seeds of Creation (2004)
userId
1        4.109617                                4.887824
2        3.461576                                3.934857
3        0.679610                                3.668610
4        3.309532                                3.643364
5        3.505025                                3.768780

                                                                             \
title  'Round Midnight (1986) 'Salem's Lot (2004) 'Til There Was You (1997)
userId
1                    4.184049            5.318414                  4.657216
2                    3.358074            4.335318                  3.734992
3                    3.300843            3.146910                  3.718725
4                    3.102344            4.050833                  3.448617
5                    3.203694            4.218931                  3.559758

                                                           \
title  'Tis the Season for Love (2015) 'burbs, The (1989)
userId
1                             2.790764           4.172614
2                             2.366645           3.274821
3                             0.211071           4.454628
4                             2.273084           2.974805
5                             2.415217           3.032339

                                                         \
title  'night Mother (1986) (500) Days of Summer (2009)
userId
1                  3.606525                    4.601844
2                  2.972925                    3.778227
3                  1.615065                    2.298713
4                  2.800085                    3.548483
5                  2.933505                    3.709816

                                       \
title  *batteries not included (1987)
userId
1                            4.224296
2                            3.450202
3                            2.393454
4                            3.228345
5                            3.365833

                          ...                                              \
title                     ...                    Zulu (2013) [REC] (2007)
userId                    ...
1                         ...                       2.051942     4.615975
2                         ...                       1.599559     3.763306
3                         ...                       2.361432     2.722128
4                         ...                       1.445413     3.516748
5                         ...                       1.467312     3.662987

                                              \
title  [REC]² (2009) [REC]³ 3 Génesis (2012)
userId
1           4.100416                3.343224
2           3.384489                2.713353
3           1.766530                2.164746
4           3.190676                2.527304
5           3.344978                2.625988

                                                                               \
title  anohana: The Flower We Saw That Day - The Movie (2013) eXistenZ (1999)
userId
1                                                3.330435            4.626869
2                                                2.770100            3.789086
3                                                1.102736            2.463288
4                                                2.625529            3.552209
5                                                2.763289            3.708725

                                                                        \
title  xXx (2002) xXx: State of the Union (2005) ¡Three Amigos! (1986)
userId
1        3.329373                       2.342388              3.849008
2        2.643782                       1.886862              3.152787
3        3.071422                       1.739840              2.037945
4        2.423080                       1.747877              2.956167
5        2.487071                       1.808663              3.086790


title  À nous la liberté (Freedom for Us) (1931)
userId
1                                       1.086718
2                                       0.813656
3                                       1.776163
4                                       0.711688
5                                       0.703608

[5 rows x 9719 columns]

In [118]:
def recommend_movies(predictions_df, userID, movies_df, original_ratings_df, num_recommendations=5):
    
    # Get and sort the user's predictions
    user_row_number = userID - 1 # UserID starts at 1, not 0
    sorted_user_predictions = predictions_df.iloc[user_row_number].sort_values(ascending=False)
   
    
    # Get the user's data and merge in the movie information.
    user_data = original_ratings_df[original_ratings_df.userId == (userID)]
    user_full = (user_data.merge(movies_df, how = 'left', left_on = 'movieId', right_on = 'movieId'))
 
    print('User {0} has already rated {1} movies.'.format(userID, user_full.shape[0]))
    print('Recommending the highest {0} predicted ratings movies not already rated.'.format(num_recommendations))
    
    # Recommend the highest predicted rating movies that the user hasn't seen yet.
    recommendations = (movies_df[~movies_df['movieId'].isin(user_full['movieId'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index()).
         rename(columns = {user_row_number: 'Ratings'}).
         sort_values('Ratings', ascending = False).
                       iloc[:num_recommendations :1])
    return user_full, recommendations

In [119]:
already_rated, predictions = recommend_movies(preds_df, 1, movies, ratings, 20)

User 1 has already rated 232 movies.
Recommending the highest 20 predicted ratings movies not already rated.

In [120]:
already_rated.sort_values('rating', ascending = False)

,movieId,title_x,userId,rating,title_y,genres
231,5060,M*A*S*H (a.k.a. MASH) (1970),1,5.0,M*A*S*H (a.k.a. MASH) (1970),Comedy|Drama|War
185,2872,Excalibur (1981),1,5.0,Excalibur (1981),Adventure|Fantasy
89,1291,Indiana Jones and the Last Crusade (1989),1,5.0,Indiana Jones and the Last Crusade (1989),Action|Adventure
90,1298,Pink Floyd: The Wall (1982),1,5.0,Pink Floyd: The Wall (1982),Drama|Musical
190,2948,From Russia with Love (1963),1,5.0,From Russia with Love (1963),Action|Adventure|Thriller
189,2947,Goldfinger (1964),1,5.0,Goldfinger (1964),Action|Adventure|Thriller
188,2944,"Dirty Dozen, The (1967)",1,5.0,"Dirty Dozen, The (1967)",Action|Drama|War
186,2899,Gulliver's Travels (1939),1,5.0,Gulliver's Travels (1939),Adventure|Animation|Children
184,2858,American Beauty (1999),1,5.0,American Beauty (1999),Drama|Romance
179,2700,"South Park: Bigger, Longer and Uncut (1999)",1,5.0,"South Park: Bigger, Longer and Uncut (1999)",Animation|Comedy|Musical
98,1517,Austin Powers: International Man of Mystery (1...,1,5.0,Austin Powers: International Man of Mystery (1...,Action|Adventure|Comedy
100,1573,Face/Off (1997),1,5.0,Face/Off (1997),Action|Crime|Drama|Thriller
102,1587,Conan the Barbarian (1982),1,5.0,Conan the Barbarian (1982),Action|Adventure|Fantasy
103,1617,L.A. Confidential (1997),1,5.0,L.A. Confidential (1997),Crime|Film-Noir|Mystery|Thriller
181,2761,"Iron Giant, The (1999)",1,5.0,"Iron Giant, The (1999)",Adventure|Animation|Children|Drama|Sci-Fi
105,1625,"Game, The (1997)",1,5.0,"Game, The (1997)",Drama|Mystery|Thriller
88,1282,Fantasia (1940),1,5.0,Fantasia (1940),Animation|Children|Fantasy|Musical
87,1278,Young Frankenstein (1974),1,5.0,Young Frankenstein (1974),Comedy|Fantasy
86,1275,Highlander (1986),1,5.0,Highlander (1986),Action|Adventure|Fantasy
85,1270,Back to the Future (1985),1,5.0,Back to the Future (1985),Adventure|Comedy|Sci-Fi
191,2949,Dr. No (1962),1,5.0,Dr. No (1962),Action|Adventure|Thriller
192,2959,Fight Club (1999),1,5.0,Fight Club (1999),Action|Crime|Drama|Thriller
82,1256,Duck Soup (1933),1,5.0,Duck Soup (1933),Comedy|Musical|War
81,1240,"Terminator, The (1984)",1,5.0,"Terminator, The (1984)",Action|Sci-Fi|Thriller
80,1226,"Quiet Man, The (1952)",1,5.0,"Quiet Man, The (1952)",Drama|Romance
79,1224,Henry V (1989),1,5.0,Henry V (1989),Action|Drama|Romance|War
78,1222,Full Metal Jacket (1987),1,5.0,Full Metal Jacket (1987),Drama|War
77,1220,"Blues Brothers, The (1980)",1,5.0,"Blues Brothers, The (1980)",Action|Comedy|Musical
151,2387,Very Bad Things (1998),1,5.0,Very Bad Things (1998),Comedy|Crime
74,1213,Goodfellas (1990),1,5.0,Goodfellas (1990),Crime|Drama
...,...,...,...,...,...,...
12,223,Clerks (1994),1,3.0,Clerks (1994),Comedy
16,296,Pulp Fiction (1994),1,3.0,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
23,423,Blown Away (1994),1,3.0,Blown Away (1994),Action|Thriller
5,70,From Dusk Till Dawn (1996),1,3.0,From Dusk Till Dawn (1996),Action|Comedy|Horror|Thriller
37,648,Mission: Impossible (1996),1,3.0,Mission: Impossible (1996),Action|Adventure|Mystery|Thriller
39,673,Space Jam (1996),1,3.0,Space Jam (1996),Adventure|Animation|Children|Comedy|Fantasy|Sc...
83,1258,"Shining, The (1980)",1,3.0,"Shining, The (1980)",Horror
41,736,Twister (1996),1,3.0,Twister (1996),Action|Adventure|Romance|Thriller
94,1408,"Last of the Mohicans, The (1992)",1,3.0,"Last of the Mohicans, The (1992)",Action|Romance|War|Western
155,2414,Young Sherlock Holmes (1985),1,3.0,Young Sherlock Holmes (1985),Action|Adventure|Children|Fantasy|Mystery|Thri...
163,2528,Logan's Run (1976),1,3.0,Logan's Run (1976),Action|Adventure|Sci-Fi
129,2093,Return to Oz (1985),1,3.0,Return to Oz (1985),Adventure|Children|Fantasy
177,2657,"Rocky Horror Picture Show, The (1975)",1,3.0,"Rocky Horror Picture Show, The (1975)",Comedy|Horror|Musical|Sci-Fi
107,1676,Starship Troopers (1997),1,3.0,Starship Troopers (1997),Action|Sci-Fi
106,1644,I Know What You Did Last Summer (1997),1,3.0,I Know What You Did Last Summer (1997),Horror|Mystery|Thriller
101,1580,Men in Black (a.k.a. MIB) (1997),1,3.0,Men in Black (a.k.a. MIB) (1997),Action|Comedy|Sci-Fi
207,3247,Sister Act (1992),1,3.0,Sister Act (1992),Comedy|Crime
95,1445,McHale's Navy (1997),1,3.0,McHale's Navy (1997),Comedy|War
93,1396,Sneakers (1992),1,3.0,Sneakers (1992),Action|Comedy|Crime|Drama|Sci-Fi
92,1377,Batman Returns (1992),1,3.0,Batman Returns (1992),Action|Crime
54,1030,Pete's Dragon (1977),1,3.0,Pete's Dragon (1977),Adventure|Animation|Children|Musical
49,1009,Escape to Witch Mountain (1975),1,3.0,Escape to Witch Mountain (1975),Adventure|Children|Fantasy
42,780,Independence Day (a.k.a. ID4) (1996),1,3.0,Independence Day (a.k.a. ID4) (1996),Action|Adventure|Sci-Fi|Thriller
206,3243,Encino Man (1992),1,3.0,Encino Man (1992),Comedy
76,1219,Psycho (1960),1,2.0,Psycho (1960),Crime|Horror
170,2617,"Mummy, The (1999)",1,2.0,"Mummy, The (1999)",Action|Adventure|Comedy|Fantasy|Horror|Thriller
143,2253,Toys (1992),1,2.0,Toys (1992),Comedy|Fantasy
148,2338,I Still Know What You Did Last Summer (1998),1,2.0,I Still Know What You Did Last Summer (1998),Horror|Mystery|Thriller
152,2389,Psycho (1998),1,2.0,Psycho (1998),Crime|Horror|Thriller
205,3176,"Talented Mr. Ripley, The (1999)",1,1.0,"Talented Mr. Ripley, The (1999)",Drama|Mystery|Thriller

In [122]:
predictions[['title','genres']]

,title,genres
5806,"Match Factory Girl, The (Tulitikkutehtaan tytt...",Comedy|Drama
8714,Villain (1971),Crime|Drama|Thriller
9118,Moonlight,Drama
3809,Galaxy of Terror (Quest) (1981),Action|Horror|Mystery|Sci-Fi
5247,"Holy Mountain, The (Montaña sagrada, La) (1973)",Drama
5194,Unfaithfully Yours (1948),Comedy
2444,Bossa Nova (2000),Comedy|Drama|Romance
4239,Umberto D. (1952),Drama
2044,Red Sorghum (Hong gao liang) (1987),Drama|War
7279,Girls About Town (1931),Comedy
2955,Rififi (Du rififi chez les hommes) (1955),Crime|Film-Noir|Thriller
5602,"Wild Parrots of Telegraph Hill, The (2003)",Documentary
4963,"Jetée, La (1962)",Romance|Sci-Fi
7448,"Separation, A (Jodaeiye Nader az Simin) (2011)",Drama
8795,Deathgasm (2015),Comedy|Horror
2379,Jonah Who Will Be 25 in the Year 2000 (Jonas q...,Comedy
8470,A Flintstones Christmas Carol (1994),Animation|Children|Comedy
7374,Submarine (2010),Comedy|Drama|Romance
5343,Sonatine (Sonachine) (1993),Action|Comedy|Crime|Drama
4354,Come and See (Idi i smotri) (1985),Drama|War